### ISSUE TITLE
Suggestion: (For POST UFS Merge), restrict access for some partitions

### ISSUE THREAD

**Issue by halal-beef** [exynos990-mainline/lk3rd#3]
This bootloader is very powerful as it is already, we have control to every partition on the device, to avoid people hard-bricking their device, should we restrict what partitions can be accessed? (e.g only those that are in the AP package in the Odin TAR Files for example)

**Comment by BotchedRPR** [comment]
Closed with commit [35f6a96](https://github.com/exynos990-mainline/lk3rd/commit/35f6a96142451b878452b7e16eb3105aa4454437)

**Comment by BotchedRPR** [comment]
Closed with commit [35f6a96](https://github.com/exynos990-mainline/lk3rd/commit/35f6a96142451b878452b7e16eb3105aa4454437)
